# Generated by Django 4.0.6 on 2022-08-25 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0095_alter_requesttype_edit_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('kind', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lims.projecttype', verbose_name='Project Type')),
                ('team_members', models.ManyToManyField(blank=True, null=True, related_name='proposals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='analysisreport',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='lims.proposal', verbose_name='Project Number'),
        ),
        migrations.AddField(
            model_name='container',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='containers', to='lims.proposal', verbose_name='Project Number'),
        ),
        migrations.AddField(
            model_name='data',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datasets', to='lims.proposal', verbose_name='Project Number'),
        ),
        migrations.AddField(
            model_name='group',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='lims.proposal', verbose_name='Proposal Number'),
        ),
        migrations.AddField(
            model_name='request',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='lims.proposal', verbose_name='Project Number'),
        ),
        migrations.AddField(
            model_name='sample',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples', to='lims.proposal', verbose_name='Proposal Number'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='lims.proposal', verbose_name='Project Number'),
        ),
    ]
