# Generated by Django 4.0.6 on 2022-08-25 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0096_proposal_analysisreport_proposal_container_proposal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='lims.proposal', verbose_name='Project Number'),
        ),
    ]
