# Generated by Django 4.2 on 2023-04-30 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0098_proposal_active_alter_group_proposal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisreport',
            name='files',
            field=models.JSONField(default=dict),
        ),
    ]
